services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=rafshan_dostavka'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5433:5432"
