spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5433/rafshan_dostavka
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    org.flywaydb: DEBUG